---
title: "Introduction to GitHub"
output: html_document
---

_Sources:_ 

* _Version Control with Git 3rd Ed, PK Ponuthorai & J Loeliger_

* _https://docs.github.com/en_

\

### Getting Started [(/get-started/)](https://docs.github.com/en/get-started/start-your-journey/creating-an-account-on-github)

GitHub is a developer platform that allows you to create, store, manage, and share your code. 

<ins>**To start using GitHub, you first need to create an account on the platform.**</ins> 



Your GitHub.com personal account is your identity on the platform, and it represents you as an individual. Having an active account allows you to collaborate on code stored on the platform. It also enables you to organize and control access to the code or repositories you store on GitHub. 

\

#### Create a repository [(/repositories/)](https://docs.github.com/en/repositories/creating-and-managing-repositories/quickstart-for-repositories)

1. Click the **New** button on the upper left of the page. This will bring you to the "Create new repository page". Provide a new repository name. 

2. Also on this page, you have the option to provide a description for the repository, followed by an option to make this repository either public or private. A public repository is discoverable and accessible to anyone who is on GitHub.com. A private repository will require the owner of the project to invite collaborators, making it less discoverable. 

3. Finally, you have the option to initialize the repository with a README.md file. Click **Create Repository**. 

***
<span style="color:red"> **PRACTICE:**</span>

Create a repository called "Introduction_to_GitHub" with the description "The place to start if you've never used GitHub before". Make this new repo public and initiate with a README. 

***

#### Add a file [(/repositories/working-with-files/)](https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository)

You can quickly add a file to the repository without cloning the repo via the **Add file** button. You can choose to 

***
<span style="color:red"> **PRACTICE:**</span>

Cut-and-paste the following into a text editor, such as TextEdit on Mac, and save to your personal machine's Desktop with the title "github-basics". Then upload the file to your Introduction_to_GitHub repository. To commit the changes, provide a brief commit message such as "My first commit." and a longer description of your choice. Finally, hit the green **Commit changes**.   

INTRODUCTORY TOPICS: 

1. Issues
2. Branching
3. Fork
4. Issues 
5. Pull Requests
6. GitHub Actions (GHA)
7. Templates

***


### Issues [(/issues/)](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues)

Use GitHub Issues to to plan, discuss, and track your work. Issues are available in all GitHub repositories and are often used for reporting bugs and requesting features. You can use Issues to collaborate on ideas or tasks, give or receive feedback, and communicate with others. 

**Quickly create issues from a repository:** [(/creating-an-issue/)](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue)

1. On GitHub.com, navigate to the main page of the repository. 

2. Under your repository name, click **Issues**. 

3. Click the green **New issue**. 

4. In the **Title** field, type a title for your issue. 

5. In the comment body field, type a description of your issue. 

6. If you're a project maintainer, you can assign the issue to someone, add it to a project, associate it with a milestone, or apply a label. 

7. When you're finished, click **Submit new issue**. 


\

***
<span style="color:red"> **PRACTICE:**</span>

Create a new issue with the title "Convert github-basics from .rtf to .md". In the description include "Replace github-basics.rtf with a Markdown file so that it is easier to read.". Submit this new issue. 

***

\ 

### Branching [(/about-branches/)](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches)

Each repository has one default branch, called the _main branch_, that reflects the most up-to-date, fully functioning project code. A _branch_ allows the user to launch a separate line of development within a software project. Therefore, you can use a branch to isolate development work without affecting the main branch or other branches in the repository. Each repository has one default branch

### Pull Requests [(/about-pull-requests/)](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)

Pull requests let you tell others about changes you've pushed to a branch in a repository on GitHub. 




